import type { Metadata } from "next";
import { Geist, Geist_Mono, Palanquin } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/others/navbar";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const palanquin = Palanquin({
  weight: ["100", "200", "300", "400", "500", "700"],
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-palanquin",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${palanquin.variable}antialiased`}
      >
        <Navbar />
        <main>{children}</main>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
